### ISSUE TITLE
PS1 cannot be loaded

### ISSUE THREAD

**Issue by ghost** [giMini/Tartarus#1]
What is going on? My PowerShell on Windows is enabled but when *.ps1 is running the error is showing:

C:\Users\...\Invoke-Tartarus.ps1cannot be loaded because running scripts is disabled on this system. 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by giMini** [comment]
Hi,

Just run the following command:

set-executionpolicy bypass –scope process
